/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import entidades.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Ariel
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal(Usuario u) {
        initComponents();
        this.setLocationRelativeTo(null);
        if ("operador".equalsIgnoreCase(u.getRol())) {
            miUsuarios.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mInicio = new javax.swing.JMenu();
        miCerrarSesion = new javax.swing.JMenuItem();
        mSalir = new javax.swing.JMenuItem();
        miIniciarSesion = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        miSalir = new javax.swing.JMenuItem();
        mPrincipal = new javax.swing.JMenu();
        mReservas = new javax.swing.JMenu();
        miEntrenamientoGrupal = new javax.swing.JMenuItem();
        miEntrenamientoPersonal = new javax.swing.JMenuItem();
        mAdministracion = new javax.swing.JMenu();
        miInstructores = new javax.swing.JMenuItem();
        miClientes = new javax.swing.JMenuItem();
        miUsuarios = new javax.swing.JMenuItem();
        mEntrenamientos = new javax.swing.JMenu();
        miEntramanientoGrupal = new javax.swing.JMenuItem();
        miEntrenamientoPersonal2 = new javax.swing.JMenuItem();
        mUtilidades = new javax.swing.JMenu();
        miReportes = new javax.swing.JMenuItem();
        mConfiguraciones = new javax.swing.JMenu();
        miCambiarClave = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1496288381_home.png"))); // NOI18N

        miCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1496288659_exit-to-app.png"))); // NOI18N
        miCerrarSesion.setText("Cerrar Sesion");
        miCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCerrarSesionActionPerformed(evt);
            }
        });
        mInicio.add(miCerrarSesion);

        mSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1496288659_exit-to-app.png"))); // NOI18N
        mSalir.setText("Salir");
        mSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSalirActionPerformed(evt);
            }
        });
        mInicio.add(mSalir);

        jMenuBar1.add(mInicio);

        miIniciarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/home-32.png"))); // NOI18N

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sign-in-32.png"))); // NOI18N
        jMenuItem2.setText("Iniciar Sesion");
        miIniciarSesion.add(jMenuItem2);

        miSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit-32.png"))); // NOI18N
        miSalir.setText("Salir");
        miIniciarSesion.add(miSalir);

        jMenuBar1.add(miIniciarSesion);

        mPrincipal.setText("Principal");

        mReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1496290481_office-15.png"))); // NOI18N
        mReservas.setText("Reservas");

        miEntrenamientoGrupal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1496289203_group_full.png"))); // NOI18N
        miEntrenamientoGrupal.setText("Entrenamiento Grupal");
        mReservas.add(miEntrenamientoGrupal);

        miEntrenamientoPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1496289451_user_full.png"))); // NOI18N
        miEntrenamientoPersonal.setText("Entremiento Personal");
        mReservas.add(miEntrenamientoPersonal);

        mPrincipal.add(mReservas);

        jMenuBar1.add(mPrincipal);

        mAdministracion.setText("Administracion");

        miInstructores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1496289451_user_full.png"))); // NOI18N
        miInstructores.setText("Instructores");
        mAdministracion.add(miInstructores);

        miClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1496289451_user_full.png"))); // NOI18N
        miClientes.setText("Clientes");
        miClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miClientesActionPerformed(evt);
            }
        });
        mAdministracion.add(miClientes);

        miUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1496289451_user_full.png"))); // NOI18N
        miUsuarios.setText("Usuarios");
        miUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUsuariosActionPerformed(evt);
            }
        });
        mAdministracion.add(miUsuarios);

        mEntrenamientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1496289905_Gym_2.png"))); // NOI18N
        mEntrenamientos.setText("Entrenamientos");

        miEntramanientoGrupal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1496289203_group_full.png"))); // NOI18N
        miEntramanientoGrupal.setText("Grupal");
        mEntrenamientos.add(miEntramanientoGrupal);

        miEntrenamientoPersonal2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1496289451_user_full.png"))); // NOI18N
        miEntrenamientoPersonal2.setText("Personal");
        mEntrenamientos.add(miEntrenamientoPersonal2);

        mAdministracion.add(mEntrenamientos);

        jMenuBar1.add(mAdministracion);

        mUtilidades.setText("Utilidades");

        miReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1496290675_office-25.png"))); // NOI18N
        miReportes.setText("Reportes");
        mUtilidades.add(miReportes);

        jMenuBar1.add(mUtilidades);

        mConfiguraciones.setText("Configuraciones");

        miCambiarClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1496288483_miscellaneous-46.png"))); // NOI18N
        miCambiarClave.setText("Cambiar Clave");
        mConfiguraciones.add(miCambiarClave);

        jMenuBar1.add(mConfiguraciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 858, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miClientesActionPerformed
        // TODO add your handling code here:
        FrmMantenimientoCliente frm = new FrmMantenimientoCliente();
        frm.setVisible(true);
        
    }//GEN-LAST:event_miClientesActionPerformed

    private void mSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mSalirActionPerformed

    private void miUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUsuariosActionPerformed
        // TODO add your handling code here:
        FrmMantenimientoUsurario frm = new FrmMantenimientoUsurario();
        frm.setVisible(true);
    }//GEN-LAST:event_miUsuariosActionPerformed

    private void miCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCerrarSesionActionPerformed
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(null,"¿Desea cerrar Sesion?");
        if (resp == JOptionPane.OK_OPTION) {
            FrmLogin frm = new FrmLogin();
            frm.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_miCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmPrincipal().setVisible(true);
//            }
//        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu mAdministracion;
    private javax.swing.JMenu mConfiguraciones;
    private javax.swing.JMenu mEntrenamientos;
    private javax.swing.JMenu mInicio;
    private javax.swing.JMenu mPrincipal;
    private javax.swing.JMenu mReservas;
    private javax.swing.JMenuItem mSalir;
    private javax.swing.JMenu mUtilidades;
    private javax.swing.JMenuItem miCambiarClave;
    private javax.swing.JMenuItem miCerrarSesion;
    private javax.swing.JMenuItem miClientes;
    private javax.swing.JMenuItem miEntramanientoGrupal;
    private javax.swing.JMenuItem miEntrenamientoGrupal;
    private javax.swing.JMenuItem miEntrenamientoPersonal;
    private javax.swing.JMenuItem miEntrenamientoPersonal2;
    private javax.swing.JMenu miIniciarSesion;
    private javax.swing.JMenuItem miInstructores;
    private javax.swing.JMenuItem miReportes;
    private javax.swing.JMenuItem miSalir;
    private javax.swing.JMenuItem miUsuarios;
    // End of variables declaration//GEN-END:variables
}
